import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Clapperboard, Video } from "lucide-react";

import Link from "next/link";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Genre {
	id: number;
	name: string;
}

async function fetchGenres(): Promise<Genre[]> {
	const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
		headers: {
			Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
		},
	});

    const data = await res.json();
	return data.genres;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const genres = await fetchGenres();

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="p-4 border-b flex justify-between items-center">
					<h1 className="text-2xl font-bold flex gap-2 items-center">
						<Clapperboard size={32} />
						<Link href="/">Movie</Link>
					</h1>

					<Link
						className="text-blue-600"
						href="/contact">
						Contact
					</Link>
				</div>

				<div className="flex">
					<div className="w-[300px] p-4 border-r flex flex-col gap-1">
						{genres.map(genre => {
							return (
								<Button
									variant="outline"
									asChild
									className="justify-start">
									<Link
										href={`/movie/${genre.id}`}
										className="flex items-center gap-2">
										<Video color="#666" />
										{genre.name}
									</Link>
								</Button>
							);
						})}
					</div>
					<div className="p-4">{children}</div>
				</div>
			</body>
		</html>
	);
}
